version: '3.9'
services:
    postgres:
      image: postgres:12-alpine
      restart: always
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=soundproof_db

    api:
      build:
        context: .
        dockerfile: Dockerfile
      restart: always
      ports:
        - 8080:8080
      environment:
        - DB_HOST=soundproof-postgres-1 
      depends_on:
        - postgres
      links:
      - postgres
