version: '3.9'
services:
    postgres:
      image: postgres:12-alpine
      restart: always
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=soundproof_db

    api:
      build:
        context: .
        dockerfile: Dockerfile
      restart: always
      ports:
        - 8080:8080
      environment:
        SERVER_PORT: '8080'
        DB_DRIVER: 'postgres'
        DB_USER: 'root'
        DB_PASSWORD: 'postgres'
        DB_HOST: 'soundproof-postgres-1'
        DB_PORT: '5432'
        DB_TABLE: 'soundproof_db'

        LOG_LEVEL: 'debug'
        LOG_FORMAT: 'console' # console or json      
      depends_on:
        - postgres
      links:
        - postgres

    migration:
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        DB_HOST: 'soundproof-postgres-1'
      command: ["./wait-for-it/wait-for-it.sh", "postgres:5432", "--", "make", "migrateup"]
      links:
        - postgres
      depends_on:
        - postgres